export const IMAGE_STYLES = [
  'Realistic Lifestyle',
  'Cinematic 4K',
  'Studio Minimalist',
  'Vintage Film',
  'Cyberpunk Neon',
  'Luxury Editorial',
  'Warm & Cozy',
  'Vibrant Pop Art',
];

export const UGC_STYLES = [
  'Spontaneous Testimonial',
  'Unboxing / Hands-on',
  'How-to / Tutorial',
  'Aesthetic Showcase',
  'POV Experience',
  'Problem & Solution',
  'Behind the Scenes',
  'ASMR',
];

export const TARGET_AUDIENCES = [
  'Gen Z, tech enthusiasts',
  'Millennials, home owners',
  'Parents of young children',
  'Fitness enthusiasts',
  'Beauty & Fashion lovers',
  'Gamers & Streamers',
  'Corporate Professionals',
  'Students & Academics',
];

export const PLATFORMS = [
  'TikTok, Instagram Reels',
  'YouTube Shorts',
  'Facebook Video',
  'LinkedIn',
  'Twitter / X',
  'Pinterest Idea Pins',
  'Amazon Video Ads',
];

export const LANGUAGES = [
  'English',
  'Italian',
  'Spanish',
  'French',
  'German',
  'Japanese',
  'Portuguese',
  'Chinese',
];

export const ASPECT_RATIOS = ['16:9', '9:16', '1:1', '4:3', '3:4'];

export const STYLE_IMAGES: Record<string, string> = {
  'Realistic Lifestyle': 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&q=80&w=400',
  'Studio Minimalist': 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&q=80&w=400',
  'Cinematic 4K': 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?auto=format&fit=crop&q=80&w=400',
  'Luxury Editorial': 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=400',
  'Vintage Film': 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&q=80&w=400',
  'Cyberpunk Neon': 'https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?auto=format&fit=crop&q=80&w=400',
  'Warm & Cozy': 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&q=80&w=400',
  'Vibrant Pop Art': 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=400',
};

export const TRANSLATIONS = {
  en: {
    title: 'UGC Ad Creator',
    subtitle: 'Transform product photos into viral video ads with BCS AI.',
    step1Title: '1. Reference Product & Configuration',
    uploadClick: 'Upload Product Images (Max 3)',
    uploadSupport: 'Add perspectives or details. Max 3 images.',
    targetLang: 'Target Language',
    targetAudience: 'Target Audience',
    platform: 'Destination Platform',
    ugcStyle: 'UGC Video Style',
    artStyle: 'Visual Art Style',
    aspectRatio: 'Aspect Ratio',
    chaosLevel: 'Creativity Level',
    chaosLow: 'Strict',
    chaosMid: 'Balanced',
    chaosHigh: 'Wild',
    modelMode: 'Model Performance',
    modeSpeed: '⚡ Speed (Flash Image)',
    modeQuality: '✨ Quality (Pro Image)',
    startBtn: 'Analyze & Create Prompt 🪄',
    step2Title: '2. Scene Generation',
    generatedPrompt: 'Generated Prompt',
    editPromptHint: 'Edit the prompt below to refine the image:',
    generateImageBtn: 'Generate Image 🎨',
    step3Title: '3. UGC Video Creation (Veo)',
    veoPrompt: 'Veo Prompt',
    editVideoPromptHint: 'Edit the prompt below to refine the video movement and audio:',
    generateVideoBtn: 'Generate Video 🎬',
    finalOutput: 'Final Output',
    download: 'Download MP4',
    downloadImage: 'Download Image',
    share: 'Share Video',
    shareNotSupported: 'Web Share not supported on this device.',
    createNew: 'Create New Project',
    logs: 'Process Logs',
    ready: 'Ready to start...',
    analyzing: 'Analyzing product images...',
    genImage: 'Generating lifestyle image...',
    analyzingScene: 'Analyzing scene...',
    genVideo: 'Generating video with Veo...',
    retryVideo: 'Retry Video Generation',
    dimensionsTitle: 'Product Dimensions (For Accurate Scale)',
    width: 'Width',
    height: 'Height',
    unit: 'Unit',
    regenerateImage: 'Regenerate Image 🔄',
    continueToVideo: 'Continue to Video ➡️',
  },
  it: {
    title: 'UGC Ad Creator',
    subtitle: 'Trasforma foto prodotti in video pubblicitari virali con BCS AI.',
    step1Title: '1. Prodotto & Configurazione',
    uploadClick: 'Carica Foto Prodotto (Max 3)',
    uploadSupport: 'Aggiungi prospettive o dettagli. Max 3 foto.',
    targetLang: 'Lingua del Video',
    targetAudience: 'Target Pubblico',
    platform: 'Piattaforma Destinazione',
    ugcStyle: 'Stile Video UGC',
    artStyle: 'Stile Artistico Visivo',
    aspectRatio: 'Formato Immagine',
    chaosLevel: 'Livello Creatività',
    chaosLow: 'Rigoroso',
    chaosMid: 'Bilanciato',
    chaosHigh: 'Selvaggio',
    modelMode: 'Performance Modello',
    modeSpeed: '⚡ Veloce (Flash Image)',
    modeQuality: '✨ Qualità (Pro Image)',
    startBtn: 'Analizza & Crea Prompt 🪄',
    step2Title: '2. Generazione Scena',
    generatedPrompt: 'Prompt Generato',
    editPromptHint: "Modifica il prompt qui sotto per perfezionare l'immagine:",
    generateImageBtn: 'Genera Immagine 🎨',
    step3Title: '3. Creazione Video UGC (Veo)',
    veoPrompt: 'Prompt Veo',
    editVideoPromptHint: 'Modifica il prompt qui sotto per perfezionare il movimento e audio:',
    generateVideoBtn: 'Genera Video 🎬',
    finalOutput: 'Output Finale',
    download: 'Scarica MP4',
    downloadImage: 'Scarica Immagine',
    share: 'Condividi Video',
    shareNotSupported: 'Condivisione Web non supportata su questo dispositivo.',
    createNew: 'Crea Nuovo Progetto',
    logs: 'Log di Processo',
    ready: 'Pronto per iniziare...',
    analyzing: 'Analisi delle immagini prodotto...',
    genImage: 'Generazione immagine lifestyle...',
    analyzingScene: 'Analisi della scena...',
    genVideo: 'Generazione video con Veo...',
    retryVideo: 'Riprova Generazione Video',
    dimensionsTitle: 'Dimensioni Prodotto (Per Scala Accurata)',
    width: 'Larghezza',
    height: 'Altezza',
    unit: 'Unità',
    regenerateImage: 'Rigenera Immagine 🔄',
    continueToVideo: 'Prosegui col Video ➡️',
  },
} as const;
