import { TransactionMapping } from '../types';

export const TRANSACTION_MAPPINGS: Record<string, TransactionMapping> = {
  BUY: {
    causale: 'BUY',
    categoriaNormalizzata: 'acquisto',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'capitalizza',
  },
  SELL: {
    causale: 'SELL',
    categoriaNormalizzata: 'vendita',
    fiscalmenteRilevante: true,
    generaRealizzo: true,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'scarico',
    trattamentoFee: 'deduci',
  },
  DEPOSIT: {
    causale: 'DEPOSIT',
    categoriaNormalizzata: 'deposito',
    fiscalmenteRilevante: false,
    generaRealizzo: false,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'nessuno',
    trattamentoFee: 'ignora',
  },
  WITHDRAWAL: {
    causale: 'WITHDRAWAL',
    categoriaNormalizzata: 'prelievo',
    fiscalmenteRilevante: false,
    generaRealizzo: false,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'nessuno',
    trattamentoFee: 'ignora',
  },
  STAKING_REWARD: {
    causale: 'STAKING_REWARD',
    categoriaNormalizzata: 'provento_staking',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  AIRDROP: {
    causale: 'AIRDROP',
    categoriaNormalizzata: 'provento_airdrop',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  REFERRAL_BONUS: {
    causale: 'REFERRAL_BONUS',
    categoriaNormalizzata: 'provento_referral',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  INTEREST: {
    causale: 'INTEREST',
    categoriaNormalizzata: 'provento_interessi',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  SIMPLE_EARN: {
    causale: 'SIMPLE_EARN',
    categoriaNormalizzata: 'provento_earn',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  LAUNCHPOOL_REWARD: {
    causale: 'LAUNCHPOOL_REWARD',
    categoriaNormalizzata: 'provento_launchpool',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  CASHBACK: {
    causale: 'CASHBACK',
    categoriaNormalizzata: 'provento_cashback',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  CONVERT: {
    causale: 'CONVERT',
    categoriaNormalizzata: 'conversione',
    fiscalmenteRilevante: true,
    generaRealizzo: true,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'scarico',
    trattamentoFee: 'deduci',
  },
  TRANSFER_IN: {
    causale: 'TRANSFER_IN',
    categoriaNormalizzata: 'trasferimento_in',
    fiscalmenteRilevante: false,
    generaRealizzo: false,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'nessuno',
    trattamentoFee: 'ignora',
  },
  TRANSFER_OUT: {
    causale: 'TRANSFER_OUT',
    categoriaNormalizzata: 'trasferimento_out',
    fiscalmenteRilevante: false,
    generaRealizzo: false,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'nessuno',
    trattamentoFee: 'ignora',
  },
  FEE: {
    causale: 'FEE',
    categoriaNormalizzata: 'commissione',
    fiscalmenteRilevante: false,
    generaRealizzo: false,
    generaProvento: false,
    aggiornaMonitoraggio: false,
    direzioneLotto: 'nessuno',
    trattamentoFee: 'deduci',
  },
  REBATE: {
    causale: 'REBATE',
    categoriaNormalizzata: 'rimborso',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  DISTRIBUTION: {
    causale: 'DISTRIBUTION',
    categoriaNormalizzata: 'distribuzione',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  MARGIN_FEE: {
    causale: 'MARGIN_FEE',
    categoriaNormalizzata: 'fee_margine',
    fiscalmenteRilevante: false,
    generaRealizzo: false,
    generaProvento: false,
    aggiornaMonitoraggio: false,
    direzioneLotto: 'nessuno',
    trattamentoFee: 'deduci',
  },
  FUTURES_SETTLEMENT: {
    causale: 'FUTURES_SETTLEMENT',
    categoriaNormalizzata: 'regolamento_futures',
    fiscalmenteRilevante: true,
    generaRealizzo: true,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'scarico',
    trattamentoFee: 'deduci',
  },
  FUTURES_FUNDING: {
    causale: 'FUTURES_FUNDING',
    categoriaNormalizzata: 'funding_futures',
    fiscalmenteRilevante: true,
    generaRealizzo: false,
    generaProvento: true,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'carico',
    trattamentoFee: 'ignora',
  },
  OPTIONS_PREMIUM: {
    causale: 'OPTIONS_PREMIUM',
    categoriaNormalizzata: 'premio_opzioni',
    fiscalmenteRilevante: true,
    generaRealizzo: true,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'scarico',
    trattamentoFee: 'deduci',
  },
  SWAP: {
    causale: 'SWAP',
    categoriaNormalizzata: 'swap',
    fiscalmenteRilevante: true,
    generaRealizzo: true,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'scarico',
    trattamentoFee: 'deduci',
  },
  DUST_CONVERSION: {
    causale: 'DUST_CONVERSION',
    categoriaNormalizzata: 'conversione_dust',
    fiscalmenteRilevante: true,
    generaRealizzo: true,
    generaProvento: false,
    aggiornaMonitoraggio: true,
    direzioneLotto: 'scarico',
    trattamentoFee: 'ignora',
  },
};

export function getTransactionMapping(causaleRaw: string): TransactionMapping | null {
  const normalized = causaleRaw.toUpperCase().trim();

  for (const [key, mapping] of Object.entries(TRANSACTION_MAPPINGS)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return mapping;
    }
  }

  return null;
}

export function getAllMappings(): TransactionMapping[] {
  return Object.values(TRANSACTION_MAPPINGS);
}
